name: cocu
description: Cost Curve - A simple mobile app to track price changes in usual purchased items at home.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"
dependencies:
  flutter:
    sdk: flutter
  sqflite_sqlcipher: ^3.4.0
  flutter_secure_storage: ^10.0.0
  path: ^1.9.0
  shared_preferences: ^2.5.3
  fl_chart: ^0.68.0
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  file_picker: ^10.3.6
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/cocu_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
